import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";

import { cn } from "@/lib/utils";
import { Header } from "@/components/Header";
import { getHeaderData } from "@/lib/getSanityData";

import "./globals.css";

const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = await getHeaderData();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("min-h-screen bg-background font-sans antialiased", interTight.className)}
      >
        {headerData && <Header data={headerData} />}
        <main>{children}</main>
      </body>
    </html>
  );
}
